language: ruby
cache: bundler
sudo: false
addons:
  postgresql: "9.6"
rvm:
  - 2.3.5
  - 2.4.2
  - 2.5.1
  - 2.6.0
  - ruby-head
  - jruby-9.1.9.0
  - jruby-9.2.5.0
  - jruby-head

gemfile:
  - gemfiles/activerecord_4.2.0.gemfile
  - gemfiles/activerecord_5.0.2.gemfile
  - gemfiles/activerecord_5.1.0.gemfile
  - gemfiles/activerecord_5.2.2.gemfile
  - gemfiles/activerecord_6.0.0.gemfile
env:
  - DB=sqlite
  - DB=postgres

matrix:
  fast_finish: true
  exclude:
  - rvm: 2.2.6
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: 2.3.5
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: 2.4.2
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/activerecord_5.0.2.gemfile
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: jruby-9.2.5.0
    gemfile: gemfiles/activerecord_5.0.2.gemfile
  - rvm: jruby-9.2.5.0
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  email:
    recipients:
      - alessandro.rodi@renuo.ch
    on_success: change
    on_failure: change
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rubocop && bundle exec rake
